FROM nfcore/base:1.9

# Create the conda environment

## this is going to be installed into:
## /opt/conda/envs

# Make sure conda installation is in the PATH 
# and so are python modules - they should be in PYTHONPATH (tip: add [..]/lib/python3.8/site-packages)


